In [1]:
import pandas as pd
import numpy as np

In [3]:
print (pd.__version__)

2.3.3

In [4]:
print (np.__version__)

2.0.2

In [7]:
!pip install -U scikit-learn
import sklearn
print (sklearn.__version__)

Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-learn
  Downloading scikit_learn-1.6.1-cp39-cp39-macosx_12_0_arm64.whl.metadata (31 kB)
Requirement already satisfied: numpy>=1.19.5 in /Users/aswathy.n/Library/Python/3.9/lib/python/site-packages (from scikit-learn) (2.0.2)
Collecting scipy>=1.6.0 (from scikit-learn)
  Downloading scipy-1.13.1-cp39-cp39-macosx_12_0_arm64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.6.1-cp39-cp39-macosx_12_0_arm64.whl (11.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.1/11.1 MB 474.3 kB/s  0:00:23m0:00:0100:01
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.13.1-cp39-cp39-macosx_12_0_arm64.whl (30.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.3/30.3 MB 1.2 MB/s  0:00:25m0:00:0100:010m
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [scikit-learn][0m [scikit-learn]
Successfully installed joblib-1.5.3 scikit-learn-1.6.1 scipy-1.13.1 threadpoolctl-3.6.0
1.6.1

In [ ]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, mean_squared_error, r2_score

In [11]:
df_churnPrediction = pd.read_csv('churn_prediction.csv')
df_churnPrediction.head()

,customer_id,vintage,age,gender,dependents,occupation,city,customer_nw_category,branch_code,current_balance,...,average_monthly_balance_prevQ,average_monthly_balance_prevQ2,current_month_credit,previous_month_credit,current_month_debit,previous_month_debit,current_month_balance,previous_month_balance,last_transaction,churn
0,1,2401,66,Male,0.0,self_employed,187.0,2,755,1458.71,...,1458.71,1449.07,0.20,0.20,0.20,0.20,1458.71,1458.71,2019-05-21,0
1,2,2648,35,Male,0.0,self_employed,NaN,2,3214,5390.37,...,7799.26,12419.41,0.56,0.56,5486.27,100.56,6496.78,8787.61,2019-11-01,0
2,4,2494,31,Male,0.0,salaried,146.0,2,41,3913.16,...,4910.17,2815.94,0.61,0.61,6046.73,259.23,5006.28,5070.14,NaT,0
3,5,2629,90,NaN,NaN,self_employed,1020.0,2,582,2291.91,...,2084.54,1006.54,0.47,0.47,0.47,2143.33,2291.91,1669.79,2019-08-06,1
4,6,1879,42,Male,2.0,self_employed,1494.0,3,388,927.72,...,1643.31,1871.12,0.33,714.61,588.62,1538.06,1157.15,1677.16,2019-11-03,1

In [12]:
df_churnPrediction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15929 entries, 0 to 15928
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   customer_id                     15929 non-null  int64
 1   vintage                         15929 non-null  int64
 2   age                             15929 non-null  int64
 3   gender                          15641 non-null  object
 4   dependents                      14581 non-null  float64
 5   occupation                      15882 non-null  object
 6   city                            15469 non-null  float64
 7   customer_nw_category            15929 non-null  int64
 8   branch_code                     15929 non-null  int64
 9   current_balance                 15929 non-null  float64
 10  previous_month_end_balance      15929 non-null  float64
 11  average_monthly_balance_prevQ   15929 non-null  float64
 12  average_monthly_balance_prevQ2  15929 non-null  float64
 13  current_month_credit            15929 non-null  float64
 14  previous_month_credit           15929 non-null  float64
 15  current_month_debit             15929 non-null  float64
 16  previous_month_debit            15929 non-null  float64
 17  current_month_balance           15929 non-null  float64
 18  previous_month_balance          15929 non-null  float64
 19  last_transaction                15929 non-null  object
 20  churn                           15929 non-null  int64
dtypes: float64(12), int64(6), object(3)
memory usage: 2.6+ MB

In [14]:
df_churnPrediction.describe(include='all'   )

,customer_id,vintage,age,gender,dependents,occupation,city,customer_nw_category,branch_code,current_balance,...,average_monthly_balance_prevQ,average_monthly_balance_prevQ2,current_month_credit,previous_month_credit,current_month_debit,previous_month_debit,current_month_balance,previous_month_balance,last_transaction,churn
count,15929.000000,15929.000000,15929.000000,15641,14581.000000,15882,15469.000000,15929.000000,15929.000000,1.592900e+04,...,1.592900e+04,1.592900e+04,1.592900e+04,1.592900e+04,1.592900e+04,1.592900e+04,1.592900e+04,1.592900e+04,15929,15929.00000
unique,NaN,NaN,NaN,2,NaN,5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,348,NaN
top,NaN,NaN,NaN,Male,NaN,self_employed,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
freq,NaN,NaN,NaN,9307,NaN,9813,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1811,NaN
mean,8497.552075,2392.421181,48.173206,NaN,0.356766,NaN,795.137759,2.221860,927.847762,7.270714e+03,...,7.432824e+03,7.183143e+03,3.279398e+03,3.419695e+03,3.498418e+03,3.466232e+03,7.362582e+03,7.438765e+03,NaN,0.18752
std,4909.768959,272.487032,17.865539,NaN,1.086206,NaN,430.402780,0.662076,937.411319,5.051341e+04,...,4.893687e+04,5.528742e+04,3.124824e+04,3.541378e+04,2.825815e+04,2.772081e+04,4.933807e+04,4.973615e+04,NaN,0.39034
min,1.000000,438.000000,1.000000,NaN,0.000000,NaN,0.000000,1.000000,1.000000,-5.503960e+03,...,1.428690e+03,-1.650610e+04,1.000000e-02,1.000000e-02,1.000000e-02,1.000000e-02,-3.374180e+03,-3.060130e+03,NaN,0.00000
25%,4245.000000,2260.000000,35.000000,NaN,0.000000,NaN,409.000000,2.000000,176.000000,1.776370e+03,...,2.168030e+03,1.821850e+03,3.100000e-01,3.300000e-01,4.100000e-01,4.100000e-01,1.988660e+03,2.077040e+03,NaN,0.00000
50%,8485.000000,2454.000000,46.000000,NaN,0.000000,NaN,834.000000,2.000000,578.000000,3.276340e+03,...,3.520020e+03,3.373320e+03,6.100000e-01,6.400000e-01,9.450000e+01,1.124800e+02,3.445410e+03,3.450510e+03,NaN,0.00000
75%,12752.000000,2593.000000,60.000000,NaN,0.000000,NaN,1096.000000,3.000000,1437.000000,6.624210e+03,...,6.675250e+03,6.532500e+03,7.075900e+02,7.718700e+02,1.393640e+03,1.357730e+03,6.658490e+03,6.679810e+03,NaN,0.00000
max,16996.000000,2776.000000,90.000000,NaN,52.000000,NaN,1648.000000,3.000000,4753.000000,5.905904e+06,...,5.700290e+06,5.010170e+06,1.764286e+06,2.361808e+06,1.764286e+06,1.414168e+06,5.778185e+06,5.720144e+06,NaN,1.00000

In [17]:
df_churnPrediction.isnull().sum()

customer_id                          0
vintage                              0
age                                  0
gender                             288
dependents                        1348
occupation                          47
city                               460
customer_nw_category                 0
branch_code                          0
current_balance                      0
previous_month_end_balance           0
average_monthly_balance_prevQ        0
average_monthly_balance_prevQ2       0
current_month_credit                 0
previous_month_credit                0
current_month_debit                  0
previous_month_debit                 0
current_month_balance                0
previous_month_balance               0
last_transaction                     0
churn                                0
dtype: int64