In [2]:
import pandas as pd
import numpy as np

In [4]:
df_bat=pd.read_csv("/Users/aswathy.n/Documents/Datasets1/batting.csv")
df_bat

FileNotFoundError: [Errno 2] No such file or directory: '/Users/aswathy.n/Documents/Datasets1/batting.csv'

In [ ]:
df_sal=pd.read_csv("/Users/aswathy.n/Documents/Datasets1/salary.csv")
df_sal

       year team_id  player_id    salary
0      1985     ATL  barkele01    870000
1      1985     ATL  bedrost01    550000
2      1985     ATL  benedbr01    545000
3      1985     ATL   campri01    633333
4      1985     ATL  ceronri01    625000
...     ...     ...        ...       ...
25570  2015     WAS  treinbl01    512800
25571  2015     WAS  ugglada01    507500
25572  2015     WAS  werthja01  21000000
25573  2015     WAS  zimmejo02  16500000
25574  2015     WAS  zimmery01  14000000

[25575 rows x 4 columns]

In [68]:
df_sal.shape

(25575, 4)

In [69]:
df_bat.describe(include='all')

,player_id,team_id,year,at_bats,hits,homeruns,runs_batted_in
count,101332,101332,101332.000000,96183.000000,96183.000000,96183.000000,95759.000000
unique,18659,149,NaN,NaN,NaN,NaN,NaN
top,mcguide01,CHN,NaN,NaN,NaN,NaN,NaN
freq,31,4818,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,1963.506533,149.970327,39.261647,2.949305,17.965163
std,NaN,NaN,38.628278,186.557072,53.310941,6.409662,26.756514
min,NaN,NaN,1871.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,1933.000000,7.000000,1.000000,0.000000,0.000000
50%,NaN,NaN,1972.000000,57.000000,11.000000,0.000000,4.000000
75%,NaN,NaN,1997.000000,251.000000,63.000000,3.000000,27.000000
max,NaN,NaN,2015.000000,716.000000,262.000000,73.000000,191.000000

In [70]:
df_sal.describe(include='all')

                year team_id  player_id        salary
count   25575.000000   25575      25575  2.557500e+04
unique           NaN      35       4963           NaN
top              NaN     CLE  moyerja01           NaN
freq             NaN     922         25           NaN
mean     2000.374389     NaN        NaN  2.008563e+06
std         8.610604     NaN        NaN  3.315706e+06
min      1985.000000     NaN        NaN  0.000000e+00
25%      1993.000000     NaN        NaN  2.750000e+05
50%      2000.000000     NaN        NaN  5.500000e+05
75%      2008.000000     NaN        NaN  2.250000e+06
max      2015.000000     NaN        NaN  3.300000e+07

In [49]:
 df_sal.describe(include=np.number)

               year        salary
count  25575.000000  2.557500e+04
mean    2000.374389  2.008563e+06
std        8.610604  3.315706e+06
min     1985.000000  0.000000e+00
25%     1993.000000  2.750000e+05
50%     2000.000000  5.500000e+05
75%     2008.000000  2.250000e+06
max     2015.000000  3.300000e+07

In [50]:
df_sal.describe(include=object)

       team_id  player_id
count    25575      25575
unique      35       4963
top        CLE  moyerja01
freq       922         25

In [55]:
df_sal.describe(exclude=object)

               year        salary
count  25575.000000  2.557500e+04
mean    2000.374389  2.008563e+06
std        8.610604  3.315706e+06
min     1985.000000  0.000000e+00
25%     1993.000000  2.750000e+05
50%     2000.000000  5.500000e+05
75%     2008.000000  2.250000e+06
max     2015.000000  3.300000e+07

In [3]:
df_merge1=pd.concat([df_bat, df_sal], keys=['batting', 'salary'], axis=1)
df_merge1

NameError: name 'df_bat' is not defined

In [71]:
df_merge=pd.merge(df_sal, df_bat, on=['player_id','team_id','year'])
df_merge.shape

(24628, 8)

In [72]:
df_merge.head()

   year team_id  player_id  salary  at_bats  hits  homeruns  runs_batted_in
0  1985     ATL  barkele01  870000     17.0   0.0       0.0             0.0
1  1985     ATL  bedrost01  550000     64.0   5.0       0.0             1.0
2  1985     ATL  benedbr01  545000    208.0  42.0       0.0            20.0
3  1985     ATL   campri01  633333     13.0   3.0       1.0             2.0
4  1985     ATL  ceronri01  625000    282.0  61.0       3.0            25.0

In [73]:
df_merge['hits'].max()

262.0

In [ ]:
#for year 1995, the team_id that got the max hits

In [74]:
df_1995=df_merge[df_merge['year']==1995]
df_1995.shape

(964, 8)

In [75]:
df_1995

,year,team_id,player_id,salary,at_bats,hits,homeruns,runs_batted_in
7099,1995,ATL,averyst01,4000000,53.0,11.0,2.0,4.0
7100,1995,ATL,bedrost01,750000,0.0,0.0,0.0,0.0
7101,1995,ATL,bellira01,550000,180.0,40.0,0.0,7.0
7102,1995,ATL,blausje01,3420000,431.0,91.0,12.0,31.0
7103,1995,ATL,borbope02,111500,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
8058,1995,TOR,spraged02,760000,521.0,127.0,18.0,74.0
8059,1995,TOR,timlimi01,500000,NaN,NaN,NaN,NaN
8060,1995,TOR,warddu01,4750000,NaN,NaN,NaN,NaN
8061,1995,TOR,whitede03,4050000,427.0,121.0,10.0,53.0
8062,1995,TOR,williwo02,175000,NaN,NaN,NaN,NaN

In [76]:
team_hits=dict(df_1995.groupby('team_id')['hits'].sum())


team_hits, max(team_hits.values())
a=max(team_hits.values())
i=list(team_hits.values()).index(a)
list(team_hits.keys())[i], a

('CLE', 1454.0)

In [13]:
team_hits

{'ATL': 1167.0,
 'BAL': 1181.0,
 'BOS': 1380.0,
 'CAL': 1362.0,
 'CHA': 1374.0,
 'CHN': 1052.0,
 'CIN': 1250.0,
 'CLE': 1454.0,
 'COL': 1394.0,
 'DET': 1141.0,
 'FLO': 1271.0,
 'HOU': 1383.0,
 'KCA': 1234.0,
 'LAN': 1214.0,
 'MIN': 1382.0,
 'ML4': 1298.0,
 'MON': 1084.0,
 'NYA': 1295.0,
 'NYN': 1320.0,
 'OAK': 1245.0,
 'PHI': 1169.0,
 'PIT': 1249.0,
 'SDN': 1287.0,
 'SEA': 1309.0,
 'SFN': 1184.0,
 'SLN': 1168.0,
 'TEX': 1263.0,
 'TOR': 1283.0}

In [77]:
df_1995.groupby('team_id')['hits'].sum().keys(), df_1995.groupby('team_id')['hits'].sum().index

(Index(['ATL', 'BAL', 'BOS', 'CAL', 'CHA', 'CHN', 'CIN', 'CLE', 'COL', 'DET',
        'FLO', 'HOU', 'KCA', 'LAN', 'MIN', 'ML4', 'MON', 'NYA', 'NYN', 'OAK',
        'PHI', 'PIT', 'SDN', 'SEA', 'SFN', 'SLN', 'TEX', 'TOR'],
       dtype='object', name='team_id'),
 Index(['ATL', 'BAL', 'BOS', 'CAL', 'CHA', 'CHN', 'CIN', 'CLE', 'COL', 'DET',
        'FLO', 'HOU', 'KCA', 'LAN', 'MIN', 'ML4', 'MON', 'NYA', 'NYN', 'OAK',
        'PHI', 'PIT', 'SDN', 'SEA', 'SFN', 'SLN', 'TEX', 'TOR'],
       dtype='object', name='team_id'))

In [78]:
df_1995.groupby('team_id')['hits'].sum().argmax()
df_1995.groupby('team_id')['hits'].sum().index[7], df_1995.groupby('team_id')['hits'].sum()[7]

('CLE', 1454.0)

In [79]:
df_merge.groupby(['year','team_id'])['hits'].sum().keys()

MultiIndex([(1985, 'ATL'),
            (1985, 'BAL'),
            (1985, 'BOS'),
            (1985, 'CAL'),
            (1985, 'CHA'),
            (1985, 'CHN'),
            (1985, 'CIN'),
            (1985, 'CLE'),
            (1985, 'DET'),
            (1985, 'HOU'),
            ...
            (2015, 'PHI'),
            (2015, 'PIT'),
            (2015, 'SDN'),
            (2015, 'SEA'),
            (2015, 'SFN'),
            (2015, 'SLN'),
            (2015, 'TBA'),
            (2015, 'TEX'),
            (2015, 'TOR'),
            (2015, 'WAS')],
           names=['year', 'team_id'], length=888)

In [80]:
df1=df_merge.groupby(['year','team_id'])['hits'].sum()
df1.loc[(1995,'CLE')]

1454.0

In [81]:
df_1995= df_merge[df_merge['year']==1995]

l=pd.Series(df_1995.groupby("team_id")['hits'].sum()).sort_values(ascending=False)[0]
team=pd.Series(df_1995.groupby("team_id")['hits'].sum()).sort_values(ascending=False).index[0]
l, team, pd.Series(df_1995.groupby("team_id")['hits'].sum())

(1454.0,
 'CLE',
 team_id
 ATL    1167.0
 BAL    1181.0
 BOS    1380.0
 CAL    1362.0
 CHA    1374.0
 CHN    1052.0
 CIN    1250.0
 CLE    1454.0
 COL    1394.0
 DET    1141.0
 FLO    1271.0
 HOU    1383.0
 KCA    1234.0
 LAN    1214.0
 MIN    1382.0
 ML4    1298.0
 MON    1084.0
 NYA    1295.0
 NYN    1320.0
 OAK    1245.0
 PHI    1169.0
 PIT    1249.0
 SDN    1287.0
 SEA    1309.0
 SFN    1184.0
 SLN    1168.0
 TEX    1263.0
 TOR    1283.0
 Name: hits, dtype: float64)

In [84]:
lt = df_merge.groupby(['year','team_id', 'hits'])['hits'].sum()
lt = df_merge.groupby(['year','team_id', 'hits']).size().reset_index().groupby(['year','team_id'])['hits'].sum()

In [89]:
lt, lt.loc[(1995,"CLE")]

(year  team_id
 1985  ATL        1126.0
       BAL        1246.0
       BOS        1463.0
       CAL         980.0
       CHA        1081.0
                   ...
 2015  SLN        1182.0
       TBA        1064.0
       TEX        1131.0
       TOR        1071.0
       WAS        1333.0
 Name: hits, Length: 888, dtype: float64,
 1305.0)

In [19]:
df_merge_gp=df_merge.groupby(['year','team_id'])['hits'].sum()

year  team_id
1985  ATL        1131.0
      BAL        1304.0
      BOS        1478.0
      CAL        1210.0
      CHA        1081.0
                  ...
2015  SLN        1198.0
      TBA        1117.0
      TEX        1131.0
      TOR        1071.0
      WAS        1343.0
Name: hits, Length: 888, dtype: float64

In [90]:
raw_Data = {'Voter_name': ['Geek1', 'Geek2', 'Geek3', 'Geek4',  
                           'Geek5', 'Geek6', 'Geek7', 'Geek8'],  
            'Voter_age': [15, 23, 25, 9, 67, 54, 42, np.NaN]} 
  
df = pd.DataFrame(raw_Data, columns = ['Voter_name', 'Voter_age']) 
df['eligibility']=df['Voter_age'].apply(lambda x: "Yes" if x>=18 else "No")
df, df.dtypes
df['eligibility']=df['eligibility'].astype('category')
df, df.dtypes

(  Voter_name  Voter_age eligibility
 0      Geek1       15.0          No
 1      Geek2       23.0         Yes
 2      Geek3       25.0         Yes
 3      Geek4        9.0          No
 4      Geek5       67.0         Yes
 5      Geek6       54.0         Yes
 6      Geek7       42.0         Yes
 7      Geek8        NaN          No,
 Voter_name       object
 Voter_age       float64
 eligibility    category
 dtype: object)

The categorical data type is useful in the following cases:

A string variable consisting of only a few different values. Converting such a string variable to a categorical variable will save some memory, see here.
The lexical order of a variable is not the same as the logical order (“one”, “two”, “three”). By converting to a categorical and specifying an order on the categories, sorting and min/max will use the logical order instead of the lexical order, see here.
As a signal to other Python libraries that this column should be treated as a categorical variable (e.g. to use suitable statistical methods or plot types).

In [7]:
s= pd.Series(['X', 'Y', 'Z', 'Aaba', 'Baca', np.nan, 'CABA', None, 'bird', 'horse', 'dog'])
df=pd.DataFrame(s, columns=["StringCol"])
df['Str_upper']=df['StringCol'].apply(lambda x:str(x).upper())
df['Str_lower']=df['StringCol'].apply(lambda x:str(x).lower())
df['Str_len']=df['StringCol'].apply(lambda x:len(str(x)))
df

   StringCol Str_upper Str_lower  Str_len
0          X         X         x        1
1          Y         Y         y        1
2          Z         Z         z        1
3       Aaba      AABA      aaba        4
4       Baca      BACA      baca        4
5        NaN       NAN       nan        3
6       CABA      CABA      caba        4
7       None      NONE      none        4
8       bird      BIRD      bird        4
9      horse     HORSE     horse        5
10       dog       DOG       dog        3

In [1]:
#non repeating elements
l= [1,2,3,1,3,6,5]
[x for x in l if l.count(x)<2]

[2, 6, 5]

In [7]:
#the combination with max product
l=[3,5,1,6,8,3,9,10,4,2]
from itertools import combinations
import numpy as np

c=list(combinations(l,3))
prodt=0
for i in c:
    if np.product(i)> prodt:
        M=i
        prodt= np.product(i)
    
M

((8, 9, 10),
 [(3, 5, 1),
  (3, 5, 6),
  (3, 5, 8),
  (3, 5, 3),
  (3, 5, 9),
  (3, 5, 10),
  (3, 5, 4),
  (3, 5, 2),
  (3, 1, 6),
  (3, 1, 8),
  (3, 1, 3),
  (3, 1, 9),
  (3, 1, 10),
  (3, 1, 4),
  (3, 1, 2),
  (3, 6, 8),
  (3, 6, 3),
  (3, 6, 9),
  (3, 6, 10),
  (3, 6, 4),
  (3, 6, 2),
  (3, 8, 3),
  (3, 8, 9),
  (3, 8, 10),
  (3, 8, 4),
  (3, 8, 2),
  (3, 3, 9),
  (3, 3, 10),
  (3, 3, 4),
  (3, 3, 2),
  (3, 9, 10),
  (3, 9, 4),
  (3, 9, 2),
  (3, 10, 4),
  (3, 10, 2),
  (3, 4, 2),
  (5, 1, 6),
  (5, 1, 8),
  (5, 1, 3),
  (5, 1, 9),
  (5, 1, 10),
  (5, 1, 4),
  (5, 1, 2),
  (5, 6, 8),
  (5, 6, 3),
  (5, 6, 9),
  (5, 6, 10),
  (5, 6, 4),
  (5, 6, 2),
  (5, 8, 3),
  (5, 8, 9),
  (5, 8, 10),
  (5, 8, 4),
  (5, 8, 2),
  (5, 3, 9),
  (5, 3, 10),
  (5, 3, 4),
  (5, 3, 2),
  (5, 9, 10),
  (5, 9, 4),
  (5, 9, 2),
  (5, 10, 4),
  (5, 10, 2),
  (5, 4, 2),
  (1, 6, 8),
  (1, 6, 3),
  (1, 6, 9),
  (1, 6, 10),
  (1, 6, 4),
  (1, 6, 2),
  (1, 8, 3),
  (1, 8, 9),
  (1, 8, 10),
  (1, 8, 4),
  (1, 8, 2),
  (1, 3, 9),
  (1, 3, 10),
  (1, 3, 4),
  (1, 3, 2),
  (1, 9, 10),
  (1, 9, 4),
  (1, 9, 2),
  (1, 10, 4),
  (1, 10, 2),
  (1, 4, 2),
  (6, 8, 3),
  (6, 8, 9),
  (6, 8, 10),
  (6, 8, 4),
  (6, 8, 2),
  (6, 3, 9),
  (6, 3, 10),
  (6, 3, 4),
  (6, 3, 2),
  (6, 9, 10),
  (6, 9, 4),
  (6, 9, 2),
  (6, 10, 4),
  (6, 10, 2),
  (6, 4, 2),
  (8, 3, 9),
  (8, 3, 10),
  (8, 3, 4),
  (8, 3, 2),
  (8, 9, 10),
  (8, 9, 4),
  (8, 9, 2),
  (8, 10, 4),
  (8, 10, 2),
  (8, 4, 2),
  (3, 9, 10),
  (3, 9, 4),
  (3, 9, 2),
  (3, 10, 4),
  (3, 10, 2),
  (3, 4, 2),
  (9, 10, 4),
  (9, 10, 2),
  (9, 4, 2),
  (10, 4, 2)])

In [1]:
#Euclidean dist
l1=[4,6,2]
l2=[3,9,1]

(sum([(x-y)**2 for x,y in zip(l1,l2) ]))**0.5
(sum([(x-y)**2 for x,y in zip(l1,l2)])**0.5)

3.3166247903554

In [12]:
# return the first recurring character
inputs = "pythoninterviewquestion"
first_recurring = [c for c in inputs if inputs.count(c) > 1][0]
first_recurring

s = ["I", "love", "python", "and", "I", "love", "coding"]
s=pd.Series(s)
# map words to boolean: has at least 2 vowels
mapp = s.map(lambda x: sum(ch in "aeiou" for ch in x.lower()) >= 2)
mapp, s[mapp]

(0    False
 1     True
 2    False
 3    False
 4    False
 5     True
 6     True
 dtype: bool,
 1      love
 5      love
 6    coding
 dtype: object)

In [64]:
df = pd.DataFrame({
    'fruit':
       ['peaches']*5 + ['apples']*5 + ['bananas']*3 + 
       ['nectarines']*3 + ['carrots']*3 + ['apricots'] 
})

df.value_counts().sort_index(ascending=True), df.value_counts().sort_index(ascending=True).sort_values(ascending=False)

(fruit
 apples        5
 apricots      1
 bananas       3
 carrots       3
 nectarines    3
 peaches       5
 dtype: int64,
 fruit
 apples        5
 peaches       5
 bananas       3
 carrots       3
 nectarines    3
 apricots      1
 dtype: int64)